title: 'Insight Minlaw'
description: Description
url: 'https://insight.mlaw.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
future: true
paginate: 12
resources_name: articles
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
facebook-pixel: 255277428824423
favicon: /images/favicon-minlaw.ico
google_analytics: UA-10405444-22
permalink: none
baseurl: ""
defaults:
  -
    scope:
      path: ""
    values:
      layout: page
staging: https://mlaw-insight-staging.netlify.com/
prod: https://mlaw-insight-prod.netlify.com/
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
